[package]
name = "lief-rs"
version = "0.1.0"
authors = ["Alexandr Yusuk <aleksandr.yusuk@apriorit.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lief-sys = { path = "lief-sys" }
