[package]
name = "lief-rs"
version = "0.1.0"
authors = [ "Alexandr Yusuk <aleksandr.yusuk@apriorit.com>" ]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
image = { version = "0.23.0", features = [ "ico" ] }
lief-sys = { path = "lief-sys" }
pipe = "0.4.0"
thiserror = "1.0.24"
widestring = "0.4.3"
